image: twistoywang/khala-build:release-1.3.0-rc

build:
  stage: build

  script:
    - cd /builds/khala-team/khala
    - cmake -H. -BRelease
    - cmake --build Release

test:
  stage: test

  script:
    - cd /builds/khala-team/khala
    - cmake -H. -BRelease
    - cmake --build Release
    - cd /builds/khala-team/khala/Release
    - ./khala_test
